version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: photer-postgres
    environment:
      POSTGRES_DB: photer_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - photer-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: photer-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - photer-network

  redis:
    image: redis:7-alpine
    container_name: photer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - photer-network

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  photer-network:
    driver: bridge
