version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: photer-postgres
    environment:
      POSTGRES_DB: photer_dev
      POSTGRES_USER: photer_user
      POSTGRES_PASSWORD: photer_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U photer_user -d photer_dev']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: photer-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@photer.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '8080:80'
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
